# Generated by Django 4.0.5 on 2022-08-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magdet_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='availability',
            name='note',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='availability',
            name='pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
