# Generated by Django 4.0.5 on 2022-08-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magdet_app', '0002_availability_name_availability_note_availability_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='note',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
